### ISSUE TITLE
Error when generating gif (gifsicle needs lossy)

### ISSUE THREAD

**Issue by axelpart** [crvshlab/capa#1]
When I tried to generate a gif using `caps-ios -o test` mp4 file is created but gif file is not created.

```shell
$ capa-ios -o test
Capturing video... Press ENTER to save

Generating GIF, please wait...
gifsicle needs lossy
Video: /Users/admin/testRightArrow.mp4
GIF: /Users/admin/testRightArrow.mp4.gif
```

**Comment by asalom** [comment]
Can you make sure that the following command succeeds? You might need to uninstall it before

```shell
brew install giflossy
```

You might need to uninstall some formulas before tryin

**Comment by axelpart** [comment]
Ok I did used the command `brew install giflossy` as you suggested and I got the following error.

```shell
Error: Cannot install giflossy because conflicting formulae are installed.
  gifsicle: because both install an `gifsicle` binary

Please `brew unlink gifsicle` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

```

Then as the error says firstly used `brew unlink gifsicle` and then again `brew install giflossy` went through successfully. When afterwards tried to generate a gif recording I got the following error: 

```shell
$ capa-ios -o test
Capturing video... Press ENTER to save

Generating GIF, please wait...
ffmpeg needs libass, fontconfig
Video: /Users/admin/test1.mp4
GIF: /Users/admin/test1.mp4.gif

```

Then I unlinked ffmpeg using `brew unlink ffmpeg` and reinstalled `brew install ffmpeg --with-libass --with-fontconfig` and voila. Everything works as expected and I am able to record a gif from my iOS simulator.

**Comment by asalom** [comment]
Great to hear! I have plans to work on a simplified installation process
